apiVersion: v1
kind: PersistentVolume
metadata:
  name: lanabot-grafana-pv
spec:
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-059a8631aef4e1cab
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lanabot-grafana-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
