apiVersion: v1
kind: Service
metadata:
  namespace: lanabot-ns
  name: lanabot-ms-service
  labels:
    env: dev
    release: v1.0
    project: lanabot-project
spec:
  selector:
    app: lanabot-microservice
  ports:
    - protocol: TCP
      port: 8443
      targetPort: 8443