apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: lana-yolo-hpa
  namespace: lanabot-ns
  labels:
    app: lana-yolo
    env: dev
    release: v1.0
    project: lanabot-project
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: lana-yolo-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
